{{- include "adp-helm-library.azure-ingress" (list . "ffc-sfd-landing-page.master-ingress") -}}
{{- define "ffc-sfd-landing-page.master-ingress" -}}
metadata:
  name: {{ .Values.name }}-master
  annotations:
    nginx.org/mergeable-ingress-type: "master"
spec:
  rules:
    - host: {{ .Values.ingress.endpoint }}.{{ .Values.ingress.server }}
      http: null
{{- end -}}
