# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfd-landing-page:
    build:
      target: development
    image: ffc-sfd-landing-page-development
    container_name: ffc-sfd-landing-page-development
    ports:
      - "3000:3000"
      - "9001:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
