- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: AUTH_HOST
  value: "http://ffc-sfd-auth.ffc-sfd"
- key: GATEWAY_HOST
  value: "https://ffc-sfd-landing-page.snd3.adp.defra.gov.uk"
- key: DATA_HOST
  value: "http://ffc-sfd-data.ffc-sfd/graphql"
- key: AHWP_HOST
  value: "https://ffc-sfd-ahwp-stub.snd3.adp.defra.gov.uk"
